apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9vay1yZHMuY3hzdW9rOHllb2phLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db_username: YWRtaW4=
  db_password: c3JpdmFyZGhhbg==

